<a href="https://colab.research.google.com/github/woneze/linear_algebra/blob/main/02_basic_calculation_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def add(A, B):
  """
  행렬의 덧셈
  입력값 : 행렬의 덧셈을 수행할 행렬 A, B
  출력값 : 행렬 A와 행렬 B의 덧셈 결과인 행렬 C
  """

  n = len(A)
  p = len(A[0])

  res = []
  for i in range(0, n):
    row = []
    for j in range(0, p):
      val = A[i][j] + B[i][j]
      row.append(val)
    res.append(row)
  return res


def subtract(A, B):
  """
  행렬의 뺄셈
  입력값 : 행렬의 뺄셈을 수행할 행렬 A, B
  출력값 : 행렬 A와 행렬 B의 뺄셈 결과인 행렬 C
  """

  n = len(A)
  p = len(A[0])

  res = []
  for i in range(0, n):
    row = []
    for j in range(0, p):
      val = A[i][j] - B[i][j]
      row.append(val)
    res.append(row)
  return res


def scalar_mul(b, A):
  """
  행렬의 스칼라 곱
  입력값 : 스칼라 곱을 수행할 스칼라 b, 행렬 A
  출력값 : 스칼라 b와 행렬 A의 스칼라 곱 결과인 행렬 C
  """

  n = len(A)
  p = len(A[0])

  res = []
  for i in range(0, n):
    row = []
    for j in range(0, p):
      val = b * A[i][j]
      row.append(val)
    res.append(row)
  return res


def ele_product(A, B):
  """
  행렬의 원소 곱
  입력값 : 행렬의 원소 곱을 수행할 행렬 A, B
  출력값 : 행렬 A와 행렬 B의 원소 곱 결과인 행렬 C
  """

  n = len(A)
  p = len(A[0])

  res = []
  for i in range(0, n):
    row = []
    for j in range(0, p):
      val = A[i][j] * B[i][j]
      row.append(val)
    res.append(row)
  return res


def matmul(A, B):
  """
  행렬의 행렬 곱
  입력값 : 행렬 곱을 수행할 행렬 A, B
  출력값 : 행렬 A와 행렬 B의 곱 결과인 행렬 res
  """

  n = len(A)
  p1 = len(A[0])
  p2 = len(B[0])

  res = []
  for i in range(0, n):
    row = []
    for j in range(0, p2):
      val = 0
      for k in range(0, p1):
        val += A[i][k] * B[k][j]
      row.append(val)
    res.append(row)
  return res

In [ ]:
A = [[2, 7], [3, 4], [6, 1]]
B = [[1, 4], [4, -1], [2, 5]]
add(A, B)

[[3, 11], [7, 3], [8, 6]]

In [ ]:
A = [[2, 7], [3, 4], [6, 1]]
B = [[1, 4], [4, -1], [2, 5]]
subtract(A, B)

[[1, 3], [-1, 5], [4, -4]]

In [ ]:
A = [[2, 7], [3, 4], [6, 1]]
b = 2
scalar_mul(b, A)

[[4, 14], [6, 8], [12, 2]]

In [ ]:
A = [[1, 5], [6, 4], [2, 7]]
B = [[5, -1], [1, 2], [4, 1]]
ele_product(A, B)

[[5, -5], [6, 8], [8, 7]]

In [ ]:
A = [[2, 7], [3, 4], [5, 2]]
B = [[3, -3, 5], [-1, 2, -1]]
matmul(A, B)

[[-1, 8, 3], [5, -1, 11], [13, -11, 23]]

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2, 7], [3, 4], [6, 1]])
B = np.array([[1, 4], [4, -1], [2, 5]])
C = A + B
print(C)

[[ 3 11]
 [ 7  3]
 [ 8  6]]


In [ ]:
A = np.array([[2, 7], [3, 4], [6, 1]])
B = np.array([[1, 4], [4, -1], [2, 5]])
C = A - B
print(C)

[[ 1  3]
 [-1  5]
 [ 4 -4]]


In [ ]:
A = np.array([[2, 7], [3, 4], [6, 1]])
b = 2
C = b * A
print(C)

[[ 4 14]
 [ 6  8]
 [12  2]]


In [ ]:
A = np.array([[1, 5], [6, 4], [2, 7]])
B = np.array([[5, -1], [1, 2], [4, 1]])
C = np.multiply(A, B)
print(C)

[[ 5 -5]
 [ 6  8]
 [ 8  7]]


In [ ]:
A = np.array([[2, 7], [3, 4], [5, 2]])
B = np.array([[3, -3, 5], [-1, 2, -1]])
C = np.matmul(A, B)
print(C)

[[ -1   8   3]
 [  5  -1  11]
 [ 13 -11  23]]
